/*
 * Molecular Evolution Model Testing
 * This is for internal use only.
 *
 * Renamed from SimPLEX on 2014-2-13
 *
 * Author: Stephen Pollard
 * Stephen.T.Pollard@gmail.com
 * 2013-12-05
 */

#include "SimPLEX.h"
#include "Options.h"
#include "Data.h"

Options options;

int main() {
    options.defaultfile = "tests/Data_test.defaults"
    options.optionsfile = "test/Data_test.options"
	options.ReadOptions();

	Data data;
	data.Initialize();

    vector<string>names = {"taxA", "taxB", "taxC", "taxD", "taxE"}; 
    vector<string>seqs = {"MTNIRKSPLIKIVNHSFIDLPTPPNISAWWNFGSLLGVCLVLQILTGLFLAMHYTSDTMTAFSSVTHICRDVNYGWIIRYMHANGASMFFCLYMHVGRGMYYGYTFSETWNIGIMLLLTVMATAFMGYVLPWGQMSFWGATVITNLLSAIPYIGTNLVEWIWGGFSVDKATLTRFFAFHFILPFIISALAAVHLLFLHETGSNNPSGITSDSDKIPHPYYMIKDILGLLMLIMLTLLVLFSPDLLGDPDNYIPANPLNTPPHIKPEWYFLFAYAILRSIPNKLGGVLALMFSILILAIIPIFHKQRGMMFRPLSQCLFWLLVADLLTLTWIGGQPVEHPFITIGQLASILYF",
                          "MINIRKTPLVKIINNSFIDLPTPSNISTWWNFGSLLGVCLILQILTGLFLAMHYTSDTATAFSSVAHICRDVNYGWFIRYMHANGASMFFCLFMHVGRGLYYGYLFPETWNIGIILLLTVMATAFMGYVLPWGQMSFWGATVITNLLSAIPYIGTNLVEWVWGGFSVDKATLTRFFAFHFILPFIISALAMVHLLFLHETGSNNPSGIPSDPDKIPYPYHTIKDILGVLFLVALMTLALFSPDLLGDPDNYTPANPLSAPPHIKPEWYFLFAYAILRSIPNKLGGVLALIFSILILTIIPLLHKQRSMMFRPLSQCLFWLLVADLLTLTWIGGQPVEHPFIIIGQLASILYF",
                          "MTNIRKTPLMKVINNSFIDLPTPSNISTWWNFGSLLGICLILQILTGLFLAMHYTSDTATAFSSITHICRDVNYGWIIRYMHANGASLFFCLYMHVGRGLYYGYMFLETWNIGIILLFATMATAFMGYVLPWGQMSFWGATVITNLLSAIPYIGTNLVEWIWGGFSVDKATLTRFFAFHFILPFIIATLATIHLLFLHETGSNNPSGIPSNSDKIPHPYYTIKDILGALLLIILMTLVLFSPDLLGDPDNYIPANPLSTPPHIKPEWYFLFAYAILRSIPNKLGGVLALILSILILAIIPLLHKQRGMMFRPLSQCLFWLLVADLLILTWIGGQPVEHPFIIIGQLASITYF",
                          "MINIRKTPLMKIVNNAFIDLPTPSNISSWWNFGSLLGICLILQILTGLFLAMHYTSDTTTAFSSVAHICRDVNYGWIIRYMHANGASMFFCLFMHVGRGLYYGYTFLETWNVGVILLLTTMATAFMGYVLPWGQMSFWGATVITNLLSAIPYIGTDLVEWIWGGFSVDKATLTRFFAFHFILPFVITALAMVHLLFLHETGSNNPTGISSDADKIPHPYYTIKDILGAMLLITLMLLVLFTPDLLGDPDNYTPANPLNTPPHIKPEWYFLFAYAILRSIPNKLGGVLALVLSILILMIVPFLHKQRSMMFRPISQCMFWILVADLLTLTWIGGQPVENPYIIIGQLASIMYF",
                          "MTNTRKTPLTKIINNSFIDLPTPSNISSWWNFGSLLGLCLITQIITGLFLSMHYTPDTSTAFSSVAHICRDVNYGWLIRYLHANGASMFFCLFVHAGRGLYYGYMLKETWNIGVILLLITMATAFMGYVLPWGQMSFWGATVITNLLSAIPYIGTNIVEWIWGGFSVDKATLNRFFAFHFILPFIIAALAMIHLLFLHETGSNNPSGLSSDSDKIPHPYFTIKDILGVIVLAILMLLVLFSPDILGDPDNYIPANPLVTPPHIKPEWYFLFAYAILRSIPNKLGGVIALAASILILMTMPIIHKQRSLMFRPFSQFTFWILVADLLTLTWIGGQPIEYPFMTIGQLASTLYF"
                          };
    for (int i = 0; i <=5; i++) {
        if (data.names_to_sequences[names[i]] != seqs[i]) {
            cout << names[i] << " has the wrong sequence" << endl;
        }
    }
    
	return 0;
}

